### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by QuarticCat** [JackThomson2/fast-counter#2]
- Replace `AtomicIsize` with `CachePadded<AtomicIsize>`
- Remove `Cargo.lock`

**Comment by JackThomson2** [comment]
Hey thanks for the suggestions, 

I've actually done suggestion 1 in this PR: https://github.com/JackThomson2/fast-counter/pull/1 it dramatically improved performance!

I'll update the pr with 2 to remove the Cargo.lock

Thanks
